services:
  garage:
    image: dxflrs/garage:v1.0.0
    entrypoint: ["/garage"]
    command: ["-c", "/etc/garage.toml", "server"]
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
volumes:
  garage-meta:
  garage-data:
