;;;; parser.lisp --- recursive-descent parser: tokens -> AST
;;;;
;;;; Pure function: (CYPHER-PARSE string) -> AST, or a Cypher syntax
;;;; error (the openCypher error taxonomy).  Grammar: the openCypher 9
;;;; subset defined in docs/cypher-implementation-plan.md section 5.2,
;;;; cross-checked against specs/openCypher/grammar/openCypher.bnf.

(in-package #:scalaxy)

(defstruct (cyparser (:constructor make-cyparser (tokens query)))
  tokens
  (pos 0)
  query)

(defun %cur (p) (nth (cyparser-pos p) (cyparser-tokens p)))
(defun %curv (p) (cytoken-value (%cur p)))
(defun %advance (p)
  (incf (cyparser-pos p))
  (%cur p))

(defun %at-kind (p kind)
  (eql (cytoken-kind (%cur p)) kind))

(defun %at-punct (p str)
  (and (%at-kind p :punct) (string= (cytoken-value (%cur p)) str)))

(defun %at-keyword (p kw)
  (and (%at-kind p :ident) (string-equal (cytoken-value (%cur p)) kw)))

(defun %perr (p kind detail)
  (let ((tok (%cur p)))
    (cypher-signal kind
                   :query (cyparser-query p)
                   :detail (format nil "~a at line ~d, column ~d"
                                   detail (cytoken-line tok) (cytoken-col tok)))))

(defun %expect-punct (p str)
  (if (%at-punct p str)
      (%advance p)
      (%perr p "UnexpectedSyntax" (format nil "expected ~s, got ~s"
                                          str (or (%curv p) "<eof>")))))

(defun %check-nonneg-int (p expr what)
  "SKIP/LIMIT arguments must be constant non-negative integers."
  (if (and (consp expr) (eq (car expr) :lit))
      (let ((v (second expr)))
        (cond
          ((and (integerp v) (>= v 0)) expr)
          ((and (numberp v) (not (integerp v)))
           (cypher-signal "InvalidArgumentType"
                          :detail (format nil "~a must be an integer, got ~a" what v)))
          ((and (integerp v) (minusp v))
           (cypher-signal "NegativeIntegerArgument"
                          :detail (format nil "~a must not be negative, got ~a" what v)))
          (t (cypher-signal "InvalidArgumentType"
                            :detail (format nil "~a must be an integer" what)))))
      expr))

(defun %expect-ident (p)
  (if (%at-kind p :ident)
      (prog1 (%curv p) (%advance p))
      (%perr p "UnexpectedSyntax" (format nil "expected identifier, got ~s" (%curv p)))))

(defun %expect-keyword (p kw)
  (if (%at-keyword p kw)
      (%advance p)
      (%perr p "UnexpectedSyntax" (format nil "expected ~a, got ~s" kw (%curv p)))))

(defun %keyword-value (p)
  "Uppercase keyword string when the current token is an ident, else NIL."
  (and (%at-kind p :ident) (string-upcase (cytoken-value (%cur p)))))

(defun cypher-parse (string)
  "Parse a Cypher query string into its AST."
  (let ((p (make-cyparser (cypher-lex string :query string) string)))
    (prog1 (parse-query p)
      (unless (%at-kind p :eof)
        (%perr p "UnexpectedSyntax" (format nil "trailing input ~s" (%curv p)))))))

(defun cypher-parse-expr (string)
  "Parse a standalone Cypher expression (used for TCK result cells)."
  (let ((p (make-cyparser (cypher-lex string :query string) string)))
    (prog1 (parse-or p)
      (unless (%at-kind p :eof)
        (%perr p "UnexpectedSyntax" (format nil "trailing input ~s" (%curv p)))))))

;;; ------------------------------------------------------------------
;;; queries and clauses

(defun parse-query (p)
  (let ((first (parse-single-query p)))
    (if (or (%at-keyword p "union") (%at-punct p ";"))
        (let ((queries (list first)) (all? nil))
          (loop
            (cond
              ((%at-punct p ";")
               (%advance p)
               (if (%at-kind p :eof)
                   (return)
                   (progn (%expect-keyword p "union") nil)))
              ((%at-keyword p "union") (%advance p))
              (t (return)))
            (when (%at-keyword p "all")
              (setf all? t)
              (%advance p))
            (push (parse-single-query p) queries))
          (list :union :queries (nreverse queries) :all all?))
        first)))

(defun parse-single-query (p)
  (let ((clauses nil) (phase :reading))
    (labels ((add (c) (push c clauses)))
      (loop
        (let ((kw (%keyword-value p)))
          (cond
            ((null kw) (return))
            ((string= kw "MATCH")
             (when (eq phase :updating) (%perr p "InvalidClauseComposition" "MATCH after updating clause"))
             (add (parse-match p)))
            ((string= kw "OPTIONAL")
             (when (eq phase :updating) (%perr p "InvalidClauseComposition" "OPTIONAL MATCH after updating clause"))
             (add (parse-match p)))
            ((string= kw "UNWIND")
             (when (eq phase :updating) (%perr p "InvalidClauseComposition" "UNWIND after updating clause"))
             (%advance p)
             (let ((e (parse-or p)))
               (%expect-keyword p "as")
               (add (list :unwind :expr e :var (ast-var (%expect-ident p))))))
            ((string= kw "WITH")
             (%advance p)
             (add (parse-projection p :with))
             (setf phase :reading))
            ((string= kw "RETURN")
             (%advance p)
             (add (parse-projection p :return))
             (setf phase :returning))
            ((string= kw "CREATE")
             (%advance p)
             (setf phase :updating)
             (add (list :create :pattern (parse-pattern p))))
            ((string= kw "MERGE")
             (%advance p)
             (setf phase :updating)
             (let ((pat (parse-pattern p)))
               (let ((on-create nil) (on-match nil))
                 (loop while (%at-keyword p "on")
                       do (%advance p)
                          (let ((which (cond ((%at-keyword p "create")
                                              (%advance p) :on-create)
                                             ((%at-keyword p "match")
                                              (%advance p) :on-match)
                                             (t (%perr p "UnexpectedSyntax"
                                                       "expected CREATE or MATCH after ON")))))
                            (%expect-keyword p "set")
                            (let ((items (parse-set-items p)))
                              (if (eq which :on-create)
                                  (setf on-create items)
                                  (setf on-match items)))))
                 (add (list :merge :pattern pat
                            :on-create on-create :on-match on-match)))))
            ((string= kw "SET")
             (%advance p)
             (setf phase :updating)
             (add (list :set :items (parse-set-items p))))
            ((string= kw "REMOVE")
             (%advance p)
             (setf phase :updating)
             (add (list :remove :items (parse-remove-items p))))
            ((string= kw "DELETE")
             (%advance p)
             (setf phase :updating)
             (add (list :delete :items (parse-expr-list p) :detach nil)))
            ((string= kw "DETACH")
             (%advance p)
             (setf phase :updating)
             (%expect-keyword p "delete")
             (add (list :delete :items (parse-expr-list p) :detach t)))
            ((string= kw "ORDER")
             (%advance p)
             (%expect-keyword p "by")
             (add (list :order :items (parse-order-specs p))))
            ((string= kw "SKIP")
             (%advance p)
             (add (list :skip :expr (%check-nonneg-int p (parse-or p) "SKIP"))))
            ((string= kw "LIMIT")
             (%advance p)
             (add (list :limit :expr (%check-nonneg-int p (parse-or p) "LIMIT"))))
            ((eq phase :returning)
             (return))
            (t (%perr p "UnexpectedSyntax" (format nil "unexpected clause ~a" kw)))))))
    (when (null clauses)
      (%perr p "UnexpectedSyntax" "empty query"))
    (cons :query (nreverse clauses))))

(defun %at-pattern-start (p)
  "True when the token stream begins a node pattern (used to recognize
bare pattern predicates in WHERE)."
  (let ((tokens (cyparser-tokens p))
        (pos (cyparser-pos p)))
    (let ((t0 (nth pos tokens)))
      (and t0
           (eql (cytoken-kind t0) :punct)
           (string= (cytoken-value t0) "(")
           (let ((t1 (nth (1+ pos) tokens)))
             (and t1
                  (or (and (eql (cytoken-kind t1) :punct)
                           (member (cytoken-value t1) '(")" ":" "{") :test #'string=))
                      (and (eql (cytoken-kind t1) :ident)
                           (let ((t2 (nth (+ 2 pos) tokens)))
                             (and t2
                                  (eql (cytoken-kind t2) :punct)
                                  (member (cytoken-value t2) '(")" ":") :test #'string=)))))))))))

(defun parse-where-pred (p)
  "Parse a WHERE predicate, recognizing a bare pattern chain as a
pattern predicate (EXISTS form)."
  (if (%at-pattern-start p)
      (list :exists :chain (parse-chain p))
      (parse-or p)))

(defun parse-match (p)
  (let ((optional? nil))
    (when (%at-keyword p "optional")
      (%advance p)
      (setf optional? t))
    (%expect-keyword p "match")
    (let ((pattern (parse-pattern p)))
      (let ((where (when (%at-keyword p "where")
                     (%advance p)
                     (parse-where-pred p))))
        (list (if optional? :optional-match :match)
              :pattern pattern :where where)))))

(defun parse-projection (p kind)
  (let ((distinct? nil))
    (when (%at-keyword p "distinct")
      (setf distinct? t)
      (%advance p))
    (let ((items (if (%at-punct p "*")
                     (progn (%advance p) nil)
                     (parse-projection-items p))))
      (let ((where (when (and (eq kind :with) (%at-keyword p "where"))
                     (%advance p)
                     (parse-where-pred p)))
            (order (when (%at-keyword p "order")
                     (%advance p)
                     (%expect-keyword p "by")
                     (parse-order-specs p))))
        (if (eq kind :with)
            (list :with :items items :distinct distinct? :where where :order order)
            (list :return :items items :distinct distinct? :order order))))))

(defun parse-projection-items (p)
  (loop collect (let ((e (parse-or p)))
                  (if (%at-keyword p "as")
                      (progn (%advance p)
                             (list :item :expr e :as (ast-var (%expect-ident p))))
                      (list :item :expr e :as nil)))
        while (when (%at-punct p ",") (%advance p) t)))

(defun parse-order-specs (p)
  (loop collect (let ((e (parse-or p)))
                  (let ((desc nil))
                    (when (and (%at-keyword p "desc") (%advance p)) (setf desc t))
                    (when (and (null desc) (%at-keyword p "asc") (%advance p)) nil)
                    (when (and (null desc) (%at-keyword p "descending") (%advance p)) (setf desc t))
                    (when (and (null desc) (%at-keyword p "ascending") (%advance p)) nil)
                    (list :spec :expr e :desc desc)))
        while (when (%at-punct p ",") (%advance p) t)))

(defun parse-set-items (p)
  (loop collect (parse-set-item p)
        while (when (%at-punct p ",") (%advance p) t)))

(defun parse-set-item (p)
  (if (%at-punct p "(")
      ;; filter on a variable, e.g. (n)-[:R]->() ... not supported v1
      (%perr p "UnexpectedSyntax" "set on sub-expression not supported")
      (let ((var (ast-var (%expect-ident p))))
        (cond
          ((%at-punct p ".")
           (%advance p)
           (let ((prop (%expect-ident p)))
             (cond
               ((%at-punct p "=")
                (%advance p)
                (list :set-prop :var var :prop prop :expr (parse-or p)))
               ((%at-punct p "+=")
                (%advance p)
                (list :add-prop :var var :prop prop :expr (parse-or p)))
               (t (%perr p "UnexpectedSyntax" "expected = or += in SET")))))
          ((%at-punct p ":")
           (%advance p)
           (list :set-label :var var :label (%expect-ident p)))
          ((%at-punct p "+=")
           (%advance p)
           (list :add-map :var var :expr (parse-or p)))
          ((%at-punct p "=")
           (%advance p)
           (let ((expr (parse-or p)))
             (if (and (consp expr) (eq (car expr) :map))
                 (list :set-map :var var :expr expr)
                 (list :set-var :var var :expr expr))))
          (t (%perr p "UnexpectedSyntax" "malformed SET item"))))))

(defun parse-remove-items (p)
  (loop collect (let ((var (ast-var (%expect-ident p))))
                  (cond
                    ((%at-punct p ".")
                     (%advance p)
                     (list :remove-prop :var var :prop (%expect-ident p)))
                    ((%at-punct p ":")
                     (%advance p)
                     (list :remove-label :var var :label (%expect-ident p)))
                    (t (%perr p "UnexpectedSyntax" "malformed REMOVE item"))))
        while (when (%at-punct p ",") (%advance p) t)))

(defun parse-expr-list (p)
  (loop collect (parse-or p)
        while (when (%at-punct p ",") (%advance p) t)))

;;; ------------------------------------------------------------------
;;; patterns

(defun %at-path-assignment (p)
  "True when the next tokens are 'ident ='."
  (and (%at-kind p :ident)
       (eql (cytoken-kind (nth (1+ (cyparser-pos p)) (cyparser-tokens p))) :punct)
       (string= (cytoken-value (nth (1+ (cyparser-pos p)) (cyparser-tokens p))) "=")))

(defun parse-pattern (p)
  "Pattern = chains separated by commas; a chain is node (rel node)*.
An optional 'var =' prefix binds the whole chain to a path variable."
  (loop collect (let ((pv (when (%at-path-assignment p)
                            (prog1 (ast-var (%curv p)) (%advance p) (%advance p)))))
                  (if pv
                      (list* :path-var pv (parse-chain p))
                      (parse-chain p)))
        while (when (%at-punct p ",") (%advance p) t)))

(defun parse-chain (p)
  (let ((elements (list (parse-node p))))
    (loop
      (let ((rel (parse-rel p)))
        (unless rel (return))
        (push rel elements)
        (push (parse-node p) elements)))
    (nreverse elements)))

(defun parse-node (p)
  (%expect-punct p "(")
  (let ((var (when (%at-kind p :ident)
               (prog1 (ast-var (%curv p)) (%advance p))))
        (labels nil)
        (props nil))
    (loop while (%at-punct p ":")
          do (%advance p)
             (push (%expect-ident p) labels))
    (when (%at-kind p :param)
      (%perr p "InvalidParameterUse" "parameter is not allowed as a node pattern"))
    (when (%at-punct p "{")
      (setf props (parse-props p)))
    (%expect-punct p ")")
    (when (null props)
      (setf props nil))
    (list :node :var var :labels (nreverse labels) :props props)))

(defun parse-props (p)
  "Map literal used as a property map: {k: expr, ...} (or a parameter)."
  (if (%at-kind p :param)
      (progn
        (let ((name (cytoken-value (%cur p))))
          (%advance p)
          (list :param name)))
      (progn
        (%expect-punct p "{")
        (let ((pairs nil))
          (loop while (not (%at-punct p "}"))
                do (let ((key (if (%at-kind p :ident)
                                  (%expect-ident p)
                                  (if (%at-kind p :string)
                                      (cytoken-value (prog1 (%cur p) (%advance p)))
                                      (%perr p "UnexpectedSyntax" "expected property key")))))
                     (%expect-punct p ":")
                     (push (cons key (parse-or p)) pairs))
                   (when (%at-punct p ",") (%advance p)))
          (%expect-punct p "}")
          (nreverse pairs)))))

(defun parse-rel (p)
  "Relationship pattern or NIL when no relationship follows."
  (cond
    ((%at-punct p "--")
     (%advance p)
     (list :rel :var nil :type nil :dir :both :props nil :min nil :max nil))
    ((%at-punct p "-->")
     (%advance p)
     (list :rel :var nil :type nil :dir :out :props nil :min nil :max nil))
    ((%at-punct p "<-->")
     ;; TCK bidirectional shorthand: matches in both directions
     (%advance p)
     (list :rel :var nil :type nil :dir :both :props nil :min nil :max nil))
    ((%at-punct p "<--")
     (%advance p)
     (list :rel :var nil :type nil :dir :in :props nil :min nil :max nil))
    ((%at-punct p "-[")
     (%advance p)
     (parse-rel-detail p :out))
    ((%at-punct p "<-[")
     (%advance p)
     (parse-rel-detail p :in))
    (t nil)))

(defun parse-rel-detail (p dir)
  (let ((var (when (%at-kind p :ident)
               (prog1 (ast-var (%curv p)) (%advance p))))
        (types nil)
        (props nil))
    (loop while (%at-punct p ":")
          do (%advance p)
             (push (%expect-ident p) types)
             (when (%at-punct p "|")
               (%perr p "NoSingleRelationshipType"
                      "legacy multiple relationship types unsupported")))
    (when (> (length types) 1)
      (%perr p "NoSingleRelationshipType" "a relationship has exactly one type"))
    (when (%at-punct p "{")
      (setf props (parse-props p)))
    (when (%at-punct p "..")
      ;; range without the asterisk: -[:T..2]- is invalid
      (%perr p "InvalidRelationshipPattern" "expected * before .."))
    (let ((min-hops nil) (max-hops nil) (var-length nil))
      (when (%at-punct p "*")
        (%advance p)
        (setf var-length t)
        (when (%at-kind p :int)
          (setf min-hops (cytoken-value (%cur p)))
          (%advance p))
        (cond
          ((%at-punct p "..")
           (%advance p)
           (cond
             ((%at-punct p "-")
              (%perr p "InvalidRelationshipPattern" "negative bound"))
             ((%at-kind p :int)
              (setf max-hops (cytoken-value (%cur p)))
              (%advance p))
             (t nil)))
          (min-hops
           ;; *N means exactly N hops (min = max = N)
           (setf max-hops min-hops))
          (t nil))
        (unless min-hops (setf min-hops 1))
        (when (and max-hops (< max-hops min-hops))
          (%perr p "UnexpectedSyntax" "invalid variable-length range")))
      (%expect-punct p "]")
      (cond
        ((%at-punct p "->")
         (%advance p)
         (when (eq dir :in)
           ;; <-...-> expresses both directions
           (setf dir :both)))
        ((%at-punct p "-")
         (%advance p)
         (when (eq dir :out)
           (setf dir :both)))
        (t (%perr p "UnexpectedSyntax" "expected -> or - after ]")))
      (if var-length
          (list :rel :var-length t :var var :type (first types) :dir dir
                :props props :min min-hops :max max-hops)
          (list :rel :var var :type (first types) :dir dir :props props
                :min min-hops :max max-hops)))))

;;; ------------------------------------------------------------------
;;; expressions (precedence climbing)

(defun parse-or (p)
  (let ((e (parse-xor p)))
    (loop while (%at-keyword p "or")
          do (%advance p)
             (setf e (list :bin :or e (parse-xor p))))
    e))

(defun parse-xor (p)
  (let ((e (parse-and p)))
    (loop while (%at-keyword p "xor")
          do (%advance p)
             (setf e (list :bin :xor e (parse-and p))))
    e))

(defun parse-and (p)
  (let ((e (parse-not p)))
    (loop while (%at-keyword p "and")
          do (%advance p)
             (setf e (list :bin :and e (parse-not p))))
    e))

(defun parse-not (p)
  (if (%at-keyword p "not")
      (progn (%advance p)
             (list :not (parse-not p)))
      (parse-comparison p)))

(defun parse-comp-operand (p)
  "A comparison operand: arithmetic expression followed by optional
null predicates (IS [NOT] NULL) or list/string predicates (IN,
STARTS WITH, ENDS WITH, CONTAINS), which bind tighter than the
comparison operators."
  (let ((e (parse-additive p)))
    (loop
      (cond
        ((%at-keyword p "is")
         (%advance p)
         (let ((neg? nil))
           (when (%at-keyword p "not")
             (setf neg? t)
             (%advance p))
           (unless (%at-keyword p "null")
             (%perr p "UnexpectedSyntax" "expected NULL after IS"))
           (%advance p)
           (setf e (list (if neg? :is-not-null :is-null) :expr e))))
        ((or (%at-keyword p "in") (%at-keyword p "starts") (%at-keyword p "ends")
             (%at-keyword p "contains"))
         (let ((kw (%keyword-value p)))
           (%advance p)
           (when (member kw '("STARTS" "ENDS") :test #'string=)
             (%expect-keyword p "with"))
           (setf e (list :bin (intern kw "KEYWORD") e (parse-additive p)))))
        (t (return))))
    e))

(defun parse-comparison (p)
  "Comparison operators chain with implicit AND (openCypher: a < b < c
means a < b AND b < c)."
  (let ((e (parse-comp-operand p))
        (chain nil))
    (loop
      (cond
        ((%at-punct p "=") (%advance p) (push (cons := (parse-comp-operand p)) chain))
        ((%at-punct p "<>") (%advance p) (push (cons :<> (parse-comp-operand p)) chain))
        ((%at-punct p "<") (%advance p) (push (cons :< (parse-comp-operand p)) chain))
        ((%at-punct p ">") (%advance p) (push (cons :> (parse-comp-operand p)) chain))
        ((%at-punct p "<=") (%advance p) (push (cons :<= (parse-comp-operand p)) chain))
        ((%at-punct p ">=") (%advance p) (push (cons :>= (parse-comp-operand p)) chain))
        ((%at-punct p "=~") (%advance p) (push (cons :=~ (parse-comp-operand p)) chain))
        (t (return))))
    (if (null chain)
        e
        (let ((links (nreverse chain)))
          (let ((acc (list :bin (caar links) e (cdar links)))
                (prev (cdar links)))
            (dolist (link (cdr links))
              (setf acc (list :bin :and acc
                              (list :bin (car link) prev (cdr link))))
              (setf prev (cdr link)))
            acc)))))

(defun parse-additive (p)
  (let ((e (parse-multiplicative p)))
    (loop
      (cond
        ((%at-punct p "+") (%advance p) (setf e (list :bin :+ e (parse-multiplicative p))))
        ((%at-punct p "-") (%advance p) (setf e (list :bin :- e (parse-multiplicative p))))
        (t (return))))
    e))

(defun parse-multiplicative (p)
  (let ((e (parse-power p)))
    (loop
      (cond
        ((%at-punct p "*") (%advance p) (setf e (list :bin :* e (parse-power p))))
        ((%at-punct p "/") (%advance p) (setf e (list :bin :/ e (parse-power p))))
        ((%at-punct p "%") (%advance p) (setf e (list :bin :% e (parse-power p))))
        (t (return))))
    e))

(defun parse-power (p)
  (let ((e (parse-unary p)))
    (loop while (%at-punct p "^")
          do (%advance p)
             (setf e (list :bin :^ e (parse-unary p))))
    e))

(defun parse-unary (p)
  (cond
    ((%at-punct p "-")
     (%advance p)
     (let ((e (parse-unary p)))
       (if (and (consp e) (eq (car e) :lit) (numberp (second e)))
           (list :lit (- (second e)))
           (list :neg e))))
    ((%at-punct p "+")
     (%advance p)
     (parse-unary p))
    (t (parse-postfix p))))

(defun parse-postfix (p)
  (let ((e (parse-primary p)))
    (loop
      (cond
        ((%at-punct p ".")
         (%advance p)
         (setf e (list :prop :expr e :prop (%expect-ident p))))
        ((%at-punct p ":")
         ;; label expression: n:Label / r:Type (boolean), with
         ;; conjunction: n:A:B means n has both A and B
         (%advance p)
         (let ((labels (list (%expect-ident p))))
           (loop while (%at-punct p ":")
                 do (%advance p)
                    (push (%expect-ident p) labels))
           (setf e (list :has-labels :expr e :labels (nreverse labels)))))
        ((%at-punct p "[")
         (%advance p)
         (cond
           ((%at-punct p "..")
            ;; list slice with implicit start: list[..end], list[..]
            (%advance p)
            (let ((end (unless (%at-punct p "]") (parse-or p))))
              (%expect-punct p "]")
              (setf e (list :slice :expr e :start nil :end end))))
           (t
            (let ((start (parse-or p)))
              (cond
                ((%at-punct p "..")
                 (%advance p)
                 (let ((end (unless (%at-punct p "]") (parse-or p))))
                   (%expect-punct p "]")
                   (setf e (list :slice :expr e :start start :end end))))
                (t
                 (%expect-punct p "]")
                 (setf e (list :idx :expr e :index start))))))))
        (t (return))))
    e))

(defun parse-primary (p)
  (cond
    ((%at-kind p :int)
     (prog1 (list :lit (cytoken-value (%cur p))) (%advance p)))
    ((%at-kind p :float)
     (prog1 (list :lit (cytoken-value (%cur p))) (%advance p)))
    ((%at-kind p :string)
     (prog1 (list :lit (cytoken-value (%cur p))) (%advance p)))
    ((%at-kind p :param)
     (prog1 (list :param (cytoken-value (%cur p))) (%advance p)))
    ((%at-punct p "(")
     (%advance p)
     (let ((e (parse-or p)))
       (%expect-punct p ")")
       e))
    ((%at-punct p "[")
     (%advance p)
     (cond
       ((%at-path-assignment p)
        ;; pattern comprehension with a path variable: [p = (a)-->(b) | p]
        (let ((pv (ast-var (prog1 (%curv p) (%advance p) (%advance p)))))
          (let ((chain (parse-chain p)))
            (let ((where (when (%at-keyword p "where")
                           (%advance p)
                           (parse-or p))))
              (%expect-punct p "|")
              (let ((out (parse-or p)))
                (%expect-punct p "]")
                (list :pcomp :chain (list* :path-var pv chain)
                      :where where :out out))))))
       ((%at-punct p "(")
        ;; pattern comprehension [(a)-->(b) (WHERE pred)? | out]
        (let ((chain (parse-chain p)))
          (let ((where (when (%at-keyword p "where")
                         (%advance p)
                         (parse-or p))))
            (%expect-punct p "|")
            (let ((out (parse-or p)))
              (%expect-punct p "]")
              (list :pcomp :chain chain :where where :out out)))))
       ((and (%at-kind p :ident)
             (eql (cytoken-kind (nth (1+ (cyparser-pos p)) (cyparser-tokens p))) :ident)
             (string-equal (cytoken-value (nth (1+ (cyparser-pos p)) (cyparser-tokens p)))
                           "IN"))
        ;; list comprehension [var IN list (WHERE pred)? (| out)?]
        (let ((var (ast-var (prog1 (%curv p) (%advance p)))))
          (%expect-keyword p "in")
          (let ((list-expr (parse-or p)))
            (let ((where (when (%at-keyword p "where")
                           (%advance p)
                           (parse-or p))))
              (let ((out (when (%at-punct p "|")
                           (%advance p)
                           (parse-or p))))
                (%expect-punct p "]")
                (list :comp :var var :list list-expr
                      :where where :out out))))))
       (t
        (let ((items (loop while (not (%at-punct p "]"))
                           collect (parse-or p)
                           while (when (%at-punct p ",") (%advance p) t))))
          (%expect-punct p "]")
          (list :list :items items)))))
    ((%at-punct p "{")
     (let ((pairs (parse-map-literal p)))
       (list :map :pairs pairs)))
    ((%at-keyword p "case")
     (%advance p)
     (let ((base (unless (%at-keyword p "when")
                   (parse-or p)))
           (clauses nil) (else nil))
       (loop while (%at-keyword p "when")
             do (%advance p)
                (let ((pred (parse-or p)))
                  (%expect-keyword p "then")
                  (push (cons pred (parse-or p)) clauses)))
       (when (%at-keyword p "else")
         (%advance p)
         (setf else (parse-or p)))
       (%expect-keyword p "end")
       (list :case :base base :clauses (nreverse clauses) :else else)))
    ((%at-keyword p "true")
     (%advance p)
     (list :lit t))
    ((%at-keyword p "false")
     (%advance p)
     (list :lit :cypher-false))
    ((%at-keyword p "null")
     (%advance p)
     (list :lit :cypher-null))
    ((%at-keyword p "exists")
     (%advance p)
     (cond
       ((%at-punct p "(")
        (%advance p)
        (let ((chain (parse-chain p)))
          (%expect-punct p ")")
          (list :exists :chain chain)))
       ((%at-punct p "{")
        ;; EXISTS { pattern [WHERE pred] } subquery form
        (%advance p)
        (let ((chain (parse-chain p)))
          (let ((where (when (%at-keyword p "where")
                         (%advance p)
                         (parse-or p))))
            (%expect-punct p "}")
            (list :exists-sub :chain chain :where where))))
       (t (%perr p "UnexpectedSyntax" "expected ( or { after EXISTS"))))
    ((%at-keyword p "count")
     (%advance p)
     (%expect-punct p "(")
     (if (%at-punct p "*")
         (progn (%advance p)
                (%expect-punct p ")")
                (list :count-*))
         (let ((distinct? (when (%at-keyword p "distinct") (%advance p) t)))
           (let ((args (parse-call-args p)))
             (list :call :fn "count" :args args :distinct distinct?)))))
    ((and (%at-kind p :ident)
          (member (%keyword-value p) '("ALL" "ANY" "NONE" "SINGLE") :test #'string=))
     (let ((kind (%keyword-value p)))
       (%advance p)
       (%expect-punct p "(")
       (let ((var (ast-var (%expect-ident p))))
         (%expect-keyword p "in")
         (let ((list-expr (parse-or p)))
           (%expect-keyword p "where")
           (let ((pred (parse-or p)))
             (%expect-punct p ")")
             (list :pred :kind (intern kind "KEYWORD") :var var
                   :list list-expr :pred pred))))))
    ((%at-kind p :ident)
     (let ((name (%curv p)))
       (%advance p)
       (if (%at-punct p "(")
           (progn (%advance p)
                  (let ((distinct? (when (%at-keyword p "distinct") (%advance p) t)))
                    (let ((args (parse-call-args p)))
                      (list :call :fn name :args args
                            :distinct distinct?))))
           (ast-var name))))
    (t (%perr p "UnexpectedSyntax" (format nil "unexpected token ~s" (%curv p))))))

(defun parse-call-args (p)
  (prog1
      (if (%at-punct p ")")
          nil
          (parse-expr-list p))
    (%expect-punct p ")")))

(defun parse-map-literal (p)
  (%expect-punct p "{")
  (let ((pairs nil))
    (loop while (not (%at-punct p "}"))
          do (let ((key (if (%at-kind p :ident)
                            (%expect-ident p)
                            (if (%at-kind p :string)
                                (cytoken-value (prog1 (%cur p) (%advance p)))
                                (%perr p "UnexpectedSyntax" "expected map key")))))
               (%expect-punct p ":")
               (push (cons key (parse-or p)) pairs))
             (when (%at-punct p ",") (%advance p)))
    (%expect-punct p "}")
    (nreverse pairs)))
