;;;; scripts/test-s3.lisp --- S3 backend smoke test (Garage-compatible)
(require :asdf)
(asdf:load-asd (merge-pathnames "../scalaxy.asd" *load-truename*))
(asdf:load-system "scalaxy")

(defun env (name default)
  (or #+sbcl (sb-ext:posix-getenv name) default))

(let* ((endpoint (env "SCALAXY_S3_ENDPOINT" "http://127.0.0.1:3900"))
       (bucket (env "SCALAXY_S3_BUCKET" "scalaxy-test"))
       (access (env "SCALAXY_S3_ACCESS_KEY" "scalaxy-test"))
       (secret (env "SCALAXY_S3_SECRET_KEY" "scalaxy-test-secret"))
       (prefix (format nil "smoke-~d/" (get-universal-time)))
       (encryption (env "SCALAXY_S3_ENCRYPTION_KEY" nil))
       (args (append (list :s3-endpoint endpoint :s3-bucket bucket
                           :s3-access-key access :s3-secret-key secret :s3-prefix prefix)
                     (and encryption (list :encryption-key (string-to-octets encryption))))))
  (format t "S3 smoke test: ~a bucket=~a prefix=~a~%" endpoint bucket prefix)
  (let ((store (apply #'scalaxy:make-store args)))
    (scalaxy:store-put store "alpha" 42)
    (scalaxy:store-put store "beta" (scalaxy:cypher-map (list (cons "ok" t))))
    (assert (= 42 (scalaxy:store-get store "alpha")))
    (assert (equal '("alpha" . 42) (assoc "alpha" (scalaxy:store-scan store "") :test #'equal)))
    ;; A fresh process/store instance must reconstruct the cache from S3.
    (let ((reloaded (apply #'scalaxy:make-store args)))
      (assert (= 42 (scalaxy:store-get reloaded "alpha")))
      (assert (scalaxy:cypher-map-p (scalaxy:store-get reloaded "beta")))
      (scalaxy:store-delete reloaded "alpha"))
    (let ((final (apply #'scalaxy:make-store args)))
      (assert (null (scalaxy:store-get final "alpha")))
      (assert (scalaxy:cypher-map-p (scalaxy:store-get final "beta"))))
  (format t "S3 smoke test passed.~%")))
