;;;; json.lisp --- minimal, dependency-free JSON encoder/decoder
;;;;
;;;; Objects decode to hash-tables (string keys); arrays decode to lists.
;;;; Encoding conventions:
;;;;   hash-table        -> object
;;;;   alist (conses)    -> object
;;;;   list / vector     -> array
;;;;   t / nil           -> true / null
;;;;   string / number   -> string / number
;;;;
;;;; Values in the database are raw octets; the web layer converts them to
;;;; hex/utf8 before encoding (see web.lisp).

(in-package #:scalaxy)

(defconstant +bs+ (code-char 92) "backslash character")
(defconstant +dq+ (code-char 34) "double-quote character")

(defun json-escape (string)
  "Escape STRING for embedding in a JSON string literal."
  (with-output-to-string (out)
    (loop for ch across string
          do (cond ((or (char= ch +dq+) (char= ch +bs+))
                    (write-char +bs+ out)
                    (write-char ch out))
                   ((char= ch #\Newline) (write-string "\\n" out))
                   ((char= ch #\Return) (write-string "\\r" out))
                   ((char= ch #\Tab) (write-string "\\t" out))
                   ((char= ch #\Backspace) (write-string "\\b" out))
                   ((char= ch #\Page) (write-string "\\f" out))
                   ((char< ch #\Space)
                    (format out "\\u~4,'0x" (char-code ch)))
                   (t (write-char ch out))))))

(defun json-encode (value)
  "Encode VALUE as a JSON string."
  (with-output-to-string (out)
    (labels ((emit (v)
               (cond
                 ((null v) (write-string "null" out))
                 ((eq v t) (write-string "true" out))
                 ((stringp v) (write-char +dq+ out)
                              (write-string (json-escape v) out)
                              (write-char +dq+ out))
                 ((integerp v) (format out "~d" v))
                 ((floatp v) (format out "~a" v))
                 ((hash-table-p v)
                  (write-char #\{ out)
                  (let ((first t))
                    (maphash (lambda (k val)
                               (unless first (write-char #\, out))
                               (setf first nil)
                               (write-char +dq+ out)
                               (write-string (json-escape k) out)
                               (write-char +dq+ out)
                               (write-char #\: out)
                               (emit val))
                             v))
                  (write-char #\} out))
                 ((consp v)
                  (if (and (consp (car v)) (atom (caar v)))
                      ;; alist (dotted pairs) -> object
                      (progn
                        (write-char #\{ out)
                        (let ((first t))
                          (dolist (pair v)
                            (unless first (write-char #\, out))
                            (setf first nil)
                            (write-char +dq+ out)
                            (write-string (json-escape (string (car pair))) out)
                            (write-char +dq+ out)
                            (write-char #\: out)
                            (emit (cdr pair))))
                        (write-char #\} out))
                      ;; list -> array
                      (progn
                        (write-char #\[ out)
                        (let ((first t))
                          (dolist (item v)
                            (unless first (write-char #\, out))
                            (setf first nil)
                            (emit item)))
                        (write-char #\] out))))
                 ((vectorp v)
                  (write-char #\[ out)
                  (let ((first t))
                    (loop for i below (length v)
                          do (unless first (write-char #\, out))
                             (setf first nil)
                             (emit (aref v i))))
                  (write-char #\] out))
                 (t (error "cannot encode ~s as JSON" v)))))
      (emit value))))

(defun json-decode (string)
  "Decode a JSON STRING into Lisp values."
  (let ((pos 0) (n (length string)))
    (labels ((peek () (and (< pos n) (char string pos)))
             (skip-ws ()
               (loop while (and (< pos n)
                                (member (char string pos)
                                        '(#\Space #\Tab #\Newline #\Return)))
                     do (incf pos)))
             (expect (ch)
               (unless (and (< pos n) (char= (char string pos) ch))
                 (error "json: expected ~c at ~d" ch pos))
               (incf pos))
             (parse-value ()
               (skip-ws)
               (let ((ch (peek)))
                 (cond
                   ((null ch) (error "json: unexpected end of input"))
                   ((char= ch #\{) (parse-object))
                   ((char= ch #\[) (parse-array))
                   ((char= ch +dq+) (parse-string))
                   ((char= ch #\t) (expect-word "true") t)
                   ((char= ch #\f) (expect-word "false") nil)
                   ((char= ch #\n) (expect-word "null") nil)
                   (t (parse-number)))))
             (expect-word (word)
               (loop for ch across word
                     do (unless (and (< pos n) (char= (char string pos) ch))
                          (error "json: expected ~s" word))
                        (incf pos)))
             (parse-string ()
               (expect +dq+)
               (with-output-to-string (out)
                 (loop
                   (when (>= pos n) (error "json: unterminated string"))
                   (let ((ch (char string pos)))
                     (incf pos)
                     (cond
                       ((char= ch +dq+) (return))
                       ((char= ch +bs+)
                        (let ((esc (char string pos)))
                          (incf pos)
                          (case esc
                            (#\n (write-char #\Newline out))
                            (#\t (write-char #\Tab out))
                            (#\r (write-char #\Return out))
                            (#\b (write-char #\Backspace out))
                            (#\f (write-char #\Page out))
                            (#\/ (write-char #\/ out))
                            (#\u
                             (let ((code (parse-hex4)))
                               (write-char (code-char code) out)))
                            (t (if (char= esc +dq+)
                                   (write-char +dq+ out)
                                   (if (char= esc +bs+)
                                       (write-char +bs+ out)
                                       (error "json: bad escape ~c" esc)))))))
                       (t (write-char ch out)))))))
             (parse-hex4 ()
               (let ((code 0))
                 (dotimes (i 4)
                   (let ((ch (char string pos)))
                     (incf pos)
                     (setf code (+ (* code 16)
                                   (cond ((digit-char-p ch) (digit-char-p ch))
                                         ((char<= #\a ch #\f)
                                          (+ 10 (- (char-code ch) (char-code #\a))))
                                         ((char<= #\A ch #\F)
                                          (+ 10 (- (char-code ch) (char-code #\A))))
                                         (t (error "json: bad unicode escape")))))))
                 code))
             (parse-number ()
               (let ((start pos))
                 (when (and (< pos n) (member (char string pos) '(#\+ #\-)))
                   (incf pos))
                 (loop while (and (< pos n) (digit-char-p (char string pos)))
                       do (incf pos))
                 (when (and (< pos n) (char= (char string pos) #\.))
                   (incf pos)
                   (loop while (and (< pos n) (digit-char-p (char string pos)))
                         do (incf pos)))
                 (when (and (< pos n) (member (char string pos) '(#\e #\E)))
                   (incf pos)
                   (when (and (< pos n) (member (char string pos) '(#\+ #\-)))
                     (incf pos))
                   (loop while (and (< pos n) (digit-char-p (char string pos)))
                         do (incf pos)))
                 (let* ((token (subseq string start pos))
                        (value (handler-case (parse-integer token)
                                 (error () (parse-float token)))))
                   (unless (member (peek) '(nil #\, #\} #\] #\Space #\Tab #\Newline #\Return))
                     (error "json: trailing junk after number"))
                   value)))
             (parse-float (token)
               (let ((v (read-from-string token)))
                 (unless (floatp v) (error "json: bad number ~s" token))
                 v))
             (parse-array ()
               (expect #\[)
               (skip-ws)
               (if (and (< pos n) (char= (char string pos) #\]))
                   (progn (incf pos) nil)
                   (let ((items nil))
                     (loop
                       (push (parse-value) items)
                       (skip-ws)
                       (let ((ch (peek)))
                         (cond ((char= ch #\,) (incf pos))
                               ((char= ch #\]) (incf pos) (return))
                               (t (error "json: expected , or ]")))))
                     (nreverse items))))
              (parse-object ()
                (expect #\{)
                (skip-ws)
                (let ((table (make-hash-table :test #'equal)))
                  (if (and (< pos n) (char= (char string pos) #\}))
                      (incf pos)
                      (loop
                        (skip-ws)
                        (let ((key (parse-string)))
                          (skip-ws)
                          (expect #\:)
                          (setf (gethash key table) (parse-value))
                          (skip-ws)
                          (let ((ch (peek)))
                            (cond ((char= ch #\,) (incf pos))
                                  ((char= ch #\}) (incf pos) (return))
                                  (t (error "json: expected , or }")))))))
                  table)))
      (let ((result (parse-value)))
        (skip-ws)
        (unless (= pos n) (error "json: trailing data at ~d" pos))
        result))))
